# Generated by Django 3.0.4 on 2020-06-14 14:02

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=300, null=True)),
                ('telephone_number', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('\\d{1,10}$')])),
                ('shop_type', models.CharField(max_length=30, null=True)),
                ('GST_IN', models.CharField(max_length=200, null=True)),
                ('bank_account_no', models.IntegerField(null=True)),
                ('IFSC_CODE', models.CharField(max_length=20, null=True)),
                ('shop_owner_name', models.CharField(max_length=300, null=True)),
                ('shop_owner_mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('\\d{1,10}$')])),
                ('address', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='notes/')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2020, 6, 14, 19, 32, 35, 324494))),
                ('content', models.TextField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_price', models.IntegerField()),
                ('item_category', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=1000)),
                ('item_image', models.ImageField(blank=True, upload_to='media/items')),
                ('stock', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_price', models.IntegerField()),
                ('item_category', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=1000)),
                ('item_image', models.ImageField(blank=True, upload_to='media/items')),
                ('quantity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee')),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_position', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('\\d{1,10}$')])),
                ('salary_per_month', models.IntegerField()),
                ('bank_account_no', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('IFSC_CODE', models.CharField(max_length=20, null=True)),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2020, 6, 14, 19, 32, 35, 324494))),
                ('full_address', models.CharField(max_length=300, null=True)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2020, 6, 14, 19, 32, 35, 324494))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
